# Generated by Django 5.0.2 on 2024-03-25 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_post_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
    ]
