# Generated by Django 5.0.3 on 2024-03-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_post_comments_count_comment_post_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at",)},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="ingredients",
        ),
        migrations.AddField(
            model_name="post",
            name="recipe_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="steps",
            field=models.TextField(blank=True, null=True),
        ),
    ]
