# Generated by Django 5.0.3 on 2024-04-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_comment_options_rename_body_post_ingredients_and_more"),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="recipe_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
            ),
        ),
    ]
