# Generated by Django 5.0.3 on 2024-04-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_post_recipe_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="recipe_id", new_name="recipe",
        ),
    ]
