# Generated by Django 5.0.3 on 2024-04-08 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_rename_recipe_id_post_recipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="post",
            name="recipe_name",
        ),
        migrations.RemoveField(
            model_name="post",
            name="steps",
        ),
        migrations.AddField(
            model_name="post",
            name="canonical_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="cuisine_type",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="host",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="meal_type",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="total_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="yields",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name="post",
            name="ingredients",
        ),
        migrations.CreateModel(
            name="Nutrients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nutrient_name",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("value", models.TextField(max_length=100)),
                (
                    "recipe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe_Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.ingredients",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="ingredients",
            field=models.ManyToManyField(blank=True, to="post.ingredients"),
        ),
    ]
