# Generated by Django 5.0.3 on 2024-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_ingredients_remove_post_recipe_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nutrients",
            old_name="recipe_id",
            new_name="recipe",
        ),
        migrations.RenameField(
            model_name="recipe_ingredients",
            old_name="ingredient_id",
            new_name="ingredient",
        ),
        migrations.RemoveField(
            model_name="post",
            name="ingredients",
        ),
        migrations.AlterField(
            model_name="nutrients",
            name="nutrient_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="nutrients",
            name="value",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="nutrients",
            constraint=models.UniqueConstraint(
                fields=("recipe", "nutrient_name"), name="unique_recipe_nutrient"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe_ingredients",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
            ),
        ),
    ]
