# Generated by Django 5.0.3 on 2024-04-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0010_rename_recipe_id_nutrients_recipe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe_ingredients",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="nutrients",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipe_ingredients",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="post",
            name="host",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image_url",
        ),
        migrations.AddField(
            model_name="post",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="nutirents",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="cuisine_type",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="meal_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="yields",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Ingredients",
        ),
        migrations.DeleteModel(
            name="Nutrients",
        ),
        migrations.DeleteModel(
            name="Recipe_Ingredients",
        ),
    ]
