# Generated by Django 5.0.3 on 2024-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0011_remove_recipe_ingredients_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="host",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
