# Generated by Django 5.0.3 on 2024-04-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("host", models.TextField(blank=True, max_length=255, null=True)),
                ("title", models.TextField(blank=True, max_length=512, null=True)),
                ("total_time", models.IntegerField(blank=True, null=True)),
                ("image_url", models.TextField()),
                ("instructions", models.TextField()),
                ("yields", models.TextField(max_length=255)),
                ("meal_type", models.TextField(max_length=255)),
                ("canonical_url", models.TextField()),
                ("cuisine_type", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Nutrients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nutrient_name",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("value", models.TextField(max_length=100)),
                (
                    "recipe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe_Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredients",
                    ),
                ),
                (
                    "recipe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
    ]
