# Generated by Django 5.0.3 on 2024-04-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe_ingredients", old_name="recipe_id", new_name="recipe",
        ),
    ]
